### ISSUE TITLE
Incorrect LP token amounts calculated during imbalanced withdrawal

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/curve-js#279] opened 2024-02-28 21:50 UTC
Please check: https://github.com/curvefi/curve-js/issues/285

**Comment by amytsang** [comment] 2024-03-26 13:35
duplicate of https://github.com/orgs/curvefi/projects/7/views/1?pane=issue&itemId=57715203

**Closed by amytsang** 2024-03-26 13:35 UTC
